### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by OmaymaS**
inference instead of infence in the slides of the first lecture.

### CODE REVIEW

**Comment by amueller** [comment]
Thanks. There is an updated version of the course  here btw: https://github.com/amueller/COMS4995-s19/

**Comment by OmaymaS** [comment]
Sorry, didn't notice I was checking and older version.
But I guess the [latest](https://github.com/amueller/COMS4995-s19/blob/master/slides/aml-01-introduction/index.html) one still has the same typo, doesn't it?

**Comment by amueller** [comment]
Seems likely, wanna send another PR?

**Comment by OmaymaS** [comment]
Sent it :)

**Pull request merged**
