### PR TITLE
Updated lecture 23 to reflect 24's slides

### PR DESCRIPTION
**Pull request by kevincherian**

### CODE REVIEW

**Comment by amueller** [comment]
thanks!

**Comment by amueller** [comment]
you missed slide 28 :(

**Comment by kevincherian** [comment]
Hi Prof, 
Do you need me to add it in now?

**Comment by amueller** [comment]
No it's fine.

Sent from phone. Please excuse spelling and brevity.

On Apr 18, 2018 12:34, "Kevin Cherian" <notifications@github.com> wrote:

Hi Prof,
Do you need me to add it in now?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/amueller/COMS4995-s18/pull/15#issuecomment-382449576>,
or mute the thread

**Pull request merged**
